# Generated by Django 5.2.17 on 2026-08-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('agent', models.CharField(max_length=255)),
                ('request', models.TextField()),
                ('data_accessed', models.TextField(blank=True, null=True)),
                ('tool', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.TextField()),
                ('approval', models.CharField(blank=True, max_length=255, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
