from django.contrib.auth.models import User
from django.db import models


class Notification(models.Model):
    """
    Stores notifications generated by the AI multi-agent system.
    """

    NOTIFICATION_TYPES = [
        ("critical_project_risk", "Critical Project Risk"),
        ("high_priority_lead", "High-Priority Lead"),
        ("overdue_payment", "Overdue Payment"),
        ("important_customer_issue", "Important Customer Issue"),
        ("approval_pending", "Approval Pending"),
        ("deadline_approaching", "Deadline Approaching"),
    ]

    PRIORITIES = [
        ("critical", "Critical"),
        ("high", "High"),
        ("medium", "Medium"),
    ]

    CHANNELS = [
        ("in_app", "In-App"),
        ("email", "Email"),
        ("whatsapp", "WhatsApp"),
    ]

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="notifications",
    )

    notification_type = models.CharField(
        max_length=50,
        choices=NOTIFICATION_TYPES,
    )

    title = models.CharField(max_length=255)

    message = models.TextField()

    priority = models.CharField(
        max_length=20,
        choices=PRIORITIES,
        default="medium",
    )

    channel = models.CharField(
        max_length=20,
        choices=CHANNELS,
        default="in_app",
    )

    is_read = models.BooleanField(default=False)

    related_id = models.CharField(
        max_length=100,
        blank=True,
        null=True,
    )

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.title} - {self.user.username}"
